### ISSUE TITLE
FileAlreadyExistsException when updating workspace(s)

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon-ide#14]
```
SEVERE: Configurator failed: Failed to copy file workspaces/main/devon-ide/settings/src/main/settings/eclipse/workspace/update/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.m2e.core.prefs.bak to /projects/devon/workspaces/main/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.m2e.core.prefs.bak
java.lang.IllegalStateException: Failed to copy file workspaces/main/devon-ide/settings/src/main/settings/eclipse/workspace/update/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.m2e.core.prefs.bak to /projects/devon/workspaces/main/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.m2e.core.prefs.bak
                at com.devonfw.ide.configurator.merge.FallbackMerger.copy(FallbackMerger.java:38)
                at com.devonfw.ide.configurator.merge.FallbackMerger.merge(FallbackMerger.java:20)
                at com.devonfw.ide.configurator.merge.DirectoryMerger.merge(DirectoryMerger.java:65)
                at com.devonfw.ide.configurator.merge.DirectoryMerger.merge(DirectoryMerger.java:69)
                at com.devonfw.ide.configurator.merge.DirectoryMerger.merge(DirectoryMerger.java:69)
                at com.devonfw.ide.configurator.merge.DirectoryMerger.merge(DirectoryMerger.java:69)
                at com.devonfw.ide.configurator.merge.DirectoryMerger.merge(DirectoryMerger.java:69)
                at com.devonfw.ide.configurator.merge.DirectoryMerger.merge(DirectoryMerger.java:69)
                at com.devonfw.ide.configurator.Configurator.createOrUpdateWorkspace(Configurator.java:80)
                at com.devonfw.ide.configurator.Configurator.run(Configurator.java:153)
                at com.devonfw.ide.configurator.Configurator.main(Configurator.java:189)
Caused by: java.nio.file.FileAlreadyExistsException: /projects/devon/workspaces/main/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.m2e.core.prefs.bak
                at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:551)
                at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
                at java.nio.file.Files.copy(Files.java:1274)
                at com.devonfw.ide.configurator.merge.FallbackMerger.copy(FallbackMerger.java:36)
                ... 10 more
```

So it seems that the copy command does not allow overwriting files by default and that needs to be fixed asap!

**Comment by hohwille** [comment]
Also interesting that a backup file (*.bak) made it into my settings and that the configurator also copies that to my workspace.

**Comment by hohwille** [comment]
Done.
