### ISSUE TITLE
NPE in configurator

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon-ide#15]
```
java.lang.NullPointerException
                at com.sun.org.apache.xerces.internal.dom.ElementImpl.setAttributeNS(ElementImpl.java:645)
                at com.devonfw.ide.configurator.merge.XmlMerger.merge(XmlMerger.java:115)
                at com.devonfw.ide.configurator.merge.XmlMerger.merge(XmlMerger.java:85)
                at com.devonfw.ide.configurator.merge.XmlMerger.merge(XmlMerger.java:80)
                at com.devonfw.ide.configurator.merge.XmlMerger.merge(XmlMerger.java:70)
                at com.devonfw.ide.configurator.merge.DirectoryMerger.merge(DirectoryMerger.java:65)
                at com.devonfw.ide.configurator.merge.DirectoryMerger.merge(DirectoryMerger.java:69)
                at com.devonfw.ide.configurator.merge.DirectoryMerger.merge(DirectoryMerger.java:69)
                at com.devonfw.ide.configurator.merge.DirectoryMerger.merge(DirectoryMerger.java:69)
                at com.devonfw.ide.configurator.merge.DirectoryMerger.merge(DirectoryMerger.java:69)
                at com.devonfw.ide.configurator.Configurator.createOrUpdateWorkspace(Configurator.java:80)
                at com.devonfw.ide.configurator.Configurator.run(Configurator.java:153)
                at com.devonfw.ide.configurator.Configurator.main(Configurator.java:189)
```
Too bad...

**Comment by hohwille** [comment]
Done.
